# Generated by Django 5.0 on 2024-01-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
    ]
